export const ROUTES = {
  splash:             '/',
  home:               '/accueil',
  login:              '/login',
  register:           '/register',
  forgotPassword:     '/mot-de-passe-oublie',
  favoris:            '/favoris',
  profile:            '/profil',
  dashboard:          '/dashboard',
  commerceDetail:     '/commerce/:id',
  commerceCreate:     '/commerce/nouveau',
  notFound:           '*',
  resetPassword: '/reinitialiser-mot-de-passe',
  adminCategories: '/admin/categories',
}
