export const ROUTES = {
  landing:            '/',
  splash:             '/splash',
  home:               '/accueil',
  login:              '/login',
  register:           '/register',
  forgotPassword:     '/mot-de-passe-oublie',
  resetPassword:      '/reinitialiser-mot-de-passe',
  verifyEmail:        '/verifier-email',
  googleCallback:     '/auth/google/callback',
  favoris:            '/favoris',
  profile:            '/profil',
  dashboard:          '/dashboard',
  notFound:           '*',
}
