"""add stats favoris vues produit_images tables

Revision ID: 97545edcb905
Revises: dac75c990165
Create Date: 2026-06-27 00:33:09.302676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97545edcb905'
down_revision = 'dac75c990165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commerce_stats',
    sa.Column('commerce_id', sa.Integer(), nullable=False),
    sa.Column('nb_vues_profile', sa.Integer(), nullable=False),
    sa.Column('nb_favoris', sa.Integer(), nullable=False),
    sa.Column('last_vue_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['commerce_id'], ['commerces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commerce_id')
    )
    op.create_table('favoris',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('commerce_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['commerce_id'], ['commerces.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'commerce_id', name='uq_favori_user_commerce')
    )
    op.create_table('produit_images',
    sa.Column('commerce_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['commerce_id'], ['commerces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vues_profile',
    sa.Column('commerce_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['commerce_id'], ['commerces.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commerces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_vendeur_produits', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commerces', schema=None) as batch_op:
        batch_op.drop_column('is_vendeur_produits')

    op.drop_table('vues_profile')
    op.drop_table('produit_images')
    op.drop_table('favoris')
    op.drop_table('commerce_stats')
    # ### end Alembic commands ###
