"""add commentaires + nb_commentaires

Revision ID: ead9a6fc2c17
Revises: 97545edcb905
Create Date: 2026-06-27 09:38:17.867329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead9a6fc2c17'
down_revision = '97545edcb905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commentaires',
    sa.Column('commerce_id', sa.Integer(), nullable=False),
    sa.Column('auteur_id', sa.Integer(), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('is_moderated', sa.Boolean(), nullable=False),
    sa.Column('moderated_at', sa.DateTime(), nullable=True),
    sa.Column('moderated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auteur_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['commerce_id'], ['commerces.id'], ),
    sa.ForeignKeyConstraint(['moderated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commerce_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nb_commentaires', sa.Integer(), nullable=True))
    op.execute("UPDATE commerce_stats SET nb_commentaires = 0")
    with op.batch_alter_table('commerce_stats', schema=None) as batch_op:
        batch_op.alter_column('nb_commentaires', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commerce_stats', schema=None) as batch_op:
        batch_op.drop_column('nb_commentaires')

    op.drop_table('commentaires')
    # ### end Alembic commands ###
